name: workflow terraform para pull-request

on:
  pull_request:
    types:
      - opened
      - synchronize 

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
      AWS_KEY_ACCESS_ID: ${{ secrets.AWS_KEY_ACCESS_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: configure aws
        run: |
          echo "Login AWS: $AWS_ACCESS_ID , $AWS_KEY_ACCESS_ID , $AWS_DEFAULT_REGION"
          aws configure set aws_access_key_id $AWS_ACCESS_ID
          aws configure set aws_secret_access_key $AWS_KEY_ACCESS_ID
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.5
      
      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan