name: workflow terraform para pull-request

on:
  pull_request:
    types:
      - opened
      - synchronize 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: configure aws
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_KEY_ACCESS_ID }}
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}

      - mame: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.5
      
      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan